#ifndef LOGGING_CATEGORIES_H
#define LOGGING_CATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(lcAudio)
Q_DECLARE_LOGGING_CATEGORY(lcNetwork)
Q_DECLARE_LOGGING_CATEGORY(lcShortcut)
Q_DECLARE_LOGGING_CATEGORY(lcSpeech)
Q_DECLARE_LOGGING_CATEGORY(lcIPC)
Q_DECLARE_LOGGING_CATEGORY(lcModel)
Q_DECLARE_LOGGING_CATEGORY(lcLLM)

#endif // LOGGING_CATEGORIES_H
